// Code generated by goctl. DO NOT EDIT.
package title

import (
	"financial_statement/internal/apiserver/handler/standard/statement/title"
	"financial_statement/internal/apiserver/middleware"
	"financial_statement/internal/apiserver/svc"

	"github.com/gin-gonic/gin"
)

func RegisterStandard_statement_titleRoute(e *gin.Engine, svcCtx *svc.ServiceContext) {
	g := e.Group("/v2/standard/statement")
	g.Use(middleware.AuthorizationMiddleware)
	g.POST("/:statement_id/title", title.TitleCreateHandle(svcCtx))
	g.GET("/:statement_id/titles", title.TitleListHandle(svcCtx))
	g.DELETE("/:statement_id/title/:title_id", title.DisableTitleHandle(svcCtx))
	g.DELETE("/:statement_id/title/:title_id/formulas", title.PreDisableTitleHandle(svcCtx))
	g.PUT("/:statement_id/title/order_by", title.OrderByTitlesHandle(svcCtx))
	g.PUT("/:statement_id/title/:title_id", title.UpdateTitleHandle(svcCtx))

}
