// Code generated by goctl. DO NOT EDIT.
package title

type CreateTitleItem struct {
	Name       string `json:"name" binding:"required,min=1,max=200"`
	ExternalId string `json:"external_id"`
	Aliases    string `json:"aliases"` //别名，json字符串，示例：["name1","name2"]
}

type CreateTitleReq struct {
	Titles      []CreateTitleItem `json:"titles"`
	StatementId uint32            `uri:"statement_id"`
}

type UpdateTitleReq struct {
	StatementId uint32 `uri:"statement_id"`
	TitleId     uint32 `uri:"title_id"`
	Name        string `json:"name" binding:"max=200"`
	ExternalId  string `json:"external_id"`
	Aliases     string `json:"aliases"` //别名，json字符串，示例：["name1","name2"]
}

type TitleListReq struct {
	StatementId uint32 `uri:"statement_id"`
	Page        uint32 `uri:"page"`
	PerPage     uint32 `uri:"per_page"`
}

type TitleListResp struct {
	Titles []Title `json:"titles"`
	Total  int64   `json:"total"`
}

type Title struct {
	ID         uint32 `json:"id"`
	Name       string `json:"name"`
	ExternalId string `json:"external_id"`
	Aliases    string `json:"aliases"` //别名，json字符串，示例：["name1","name2"]
	Status     int    `json:"status"`
}

type DisableTitleReq struct {
	StatementId uint32 `uri:"statement_id"`
	TitleId     uint32 `uri:"title_id"`
	Status      int    `json:"status"`
}

type PreDisableTitleResp struct {
	FormulaIdList []uint32 `json:"formula_id_list"` //公式id集合，当为空时，说明该科目没有被任何公式所使用
}

type OrderByTitlesReq struct {
	StatementId uint32   `uri:"statement_id"`
	TitleIdList []uint32 `json:"title_id_list"` //排序后的id顺序
}
