// Code generated by goctl. DO NOT EDIT.
package downlaod

type FileReq struct {
	Uid      uint32 `uri:"uid"`
	TaskId   uint32 `uri:"task_id"`
	Date     string `uri:"date"`
	FileName string `uri:"file_name"`
}

type FileResp struct {
	File []byte `json:"file"`
}
