// Code generated by goctl. DO NOT EDIT.
package convert

import "mime/multipart"

type FileConvertReq struct {
	File *multipart.FileHeader `form:"file"` //文件流
}

type FileConvertResp struct {
	Files []string `json:"files"` //文件base64数组
}
