// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCaptcha = "captchas"

// Captcha mapped from table <captchas>
type Captcha struct {
	ID        uint32 `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true" json:"id"`
	Captcha   string `gorm:"column:captcha;type:varchar(128);not null" json:"captcha"`      // 验证码
	CaptchaID string `gorm:"column:captcha_id;type:varchar(32);not null" json:"captcha_id"` // 会话id
	CreatedAt int64  `gorm:"column:created_at;type:bigint(20);not null" json:"created_at"`  // 创建时间
	Expiry    int64  `gorm:"column:expiry;type:bigint(20);not null" json:"expiry"`          // 过期时间
}

// TableName Captcha's table name
func (*Captcha) TableName() string {
	return TableNameCaptcha
}
