// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFormulaTitleMap = "formula_title_map"

// FormulaTitleMap mapped from table <formula_title_map>
type FormulaTitleMap struct {
	FormulaID uint32 `gorm:"column:formula_id;type:int(11) unsigned;not null" json:"formula_id"`
	TitleID   uint32 `gorm:"column:title_id;type:int(11) unsigned;not null" json:"title_id"`
}

// TableName FormulaTitleMap's table name
func (*FormulaTitleMap) TableName() string {
	return TableNameFormulaTitleMap
}
