// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLoginToken = "login_tokens"

// LoginToken mapped from table <login_tokens>
type LoginToken struct {
	Token     string `gorm:"column:token;type:varchar(128);primaryKey" json:"token"`
	UserID    uint32 `gorm:"column:user_id;type:int(11) unsigned;not null" json:"user_id"`
	CreatedAt int64  `gorm:"column:created_at;type:bigint(20);not null" json:"created_at"`
	Expiry    int64  `gorm:"column:expiry;type:bigint(20);not null" json:"expiry"`
}

// TableName LoginToken's table name
func (*LoginToken) TableName() string {
	return TableNameLoginToken
}
