// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLog = "logs"

// Log mapped from table <logs>
type Log struct {
	ID        uint32 `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true" json:"id"`
	TaskID    uint32 `gorm:"column:task_id;type:int(11) unsigned;not null" json:"task_id"` // task id
	Msg       string `gorm:"column:msg;type:varchar(3000);not null" json:"msg"`
	CreatedAt int64  `gorm:"column:created_at;type:bigint(20);not null" json:"created_at"`
	UpdatedAt int64  `gorm:"column:updated_at;type:bigint(20);not null" json:"updated_at"`
	DeletedAt *int64 `gorm:"column:deleted_at;type:bigint(20)" json:"deleted_at"`
}

// TableName Log's table name
func (*Log) TableName() string {
	return TableNameLog
}
