// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameStandardStatementFormula = "standard_statement_formulas"

// StandardStatementFormula mapped from table <standard_statement_formulas>
type StandardStatementFormula struct {
	ID          uint32 `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true" json:"id"`
	StatementID uint32 `gorm:"column:statement_id;type:int(11) unsigned;not null" json:"statement_id"`
	Left        string `gorm:"column:left;type:varchar(2048);not null" json:"left"`   // 等号左边公式
	Right       string `gorm:"column:right;type:varchar(2048);not null" json:"right"` // 等号右边公式
	/*
		状态：
		1：正常
		-1：删除
	*/
	Status   int32 `gorm:"column:status;type:int(11);not null" json:"status"`
	CreateAt int64 `gorm:"column:create_at;type:bigint(20);not null" json:"create_at"`
	UpdateAt int64 `gorm:"column:update_at;type:bigint(20);not null" json:"update_at"`
}

// TableName StandardStatementFormula's table name
func (*StandardStatementFormula) TableName() string {
	return TableNameStandardStatementFormula
}
