// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTask = "tasks"

// Task mapped from table <tasks>
type Task struct {
	ID           uint32 `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true" json:"id"`
	TaskName     string `gorm:"column:task_name;type:varchar(1024);not null" json:"task_name"`
	FileFormat   string `gorm:"column:file_format;type:varchar(16);not null" json:"file_format"`
	StandardID   uint32 `gorm:"column:standard_id;type:int(11) unsigned;not null" json:"standard_id"`
	ExternalInfo string `gorm:"column:external_info;type:longtext;not null" json:"external_info"`
	Async        int32  `gorm:"column:async;type:int(11);not null" json:"async"`
	AsyncStatus  int32  `gorm:"column:async_status;type:int(11);not null;default:1" json:"async_status"` // 1：未同步，10已同步，20同步失败
	/*
		//已删除
		TaskStatusDeleted = -1
		//创建任务中
		TaskStatusCreateTasking = 1
		//任务创建完成
		TaskStatusCreated = 10
		//识别中
		TaskStatusOcring = 20
		//识别失败
		TaskStatusOcrFailed = 90
		//识别成功
		TaskStatusOcrSuccess = 100
		//已回传
		TaskStatusCallbacked = 110
	*/
	Status         int32   `gorm:"column:status;type:int(11);not null" json:"status"`
	CreaterUserID  uint32  `gorm:"column:creater_user_id;type:int(11) unsigned;not null" json:"creater_user_id"`
	StandardResult *string `gorm:"column:standard_result;type:longtext" json:"standard_result"` // 财报结构化结果
	Files          string  `gorm:"column:files;type:text;not null" json:"files"`                // 该任务对应的原始文件存放路径["xxx/xxx.jpg","xxx/xxx/jpg"]
	Error          *string `gorm:"column:error;type:varchar(4096)" json:"error"`
	CreatedAt      int64   `gorm:"column:created_at;type:bigint(20);not null" json:"created_at"`
	UpdatedAt      int64   `gorm:"column:updated_at;type:bigint(20);not null" json:"updated_at"`
}

// TableName Task's table name
func (*Task) TableName() string {
	return TableNameTask
}
