// Code generated by goctl. DO NOT EDIT.
package unauthorization

import (
	"financial_statement/internal/apiserver/handler/user/unauthorization"
	"financial_statement/internal/apiserver/svc"

	"github.com/gin-gonic/gin"
)

func RegisterUserUnauthorizationRoute(e *gin.Engine, svcCtx *svc.ServiceContext) {
	g := e.Group("/v2/user")
	g.POST("/pangu", unauthorization.UserPanguHandle(svcCtx))
	g.POST("/login", unauthorization.UserLoginHandle(svcCtx))
	g.GET("/logout", unauthorization.UserLogoutHandle(svcCtx))
	g.GET("/sso/ticket/verification", unauthorization.SsoTicketVerificationHandle(svcCtx))
	g.POST("/updatepwd", unauthorization.UserUpdatePwdHandle(svcCtx))

}
