// Code generated by goctl. DO NOT EDIT.
package downlaod

import (
	"financial_statement/internal/apiserver/handler/file/downlaod"
	"financial_statement/internal/apiserver/middleware"
	"financial_statement/internal/apiserver/svc"

	"github.com/gin-gonic/gin"
)

func RegisterFile_downlaodRoute(e *gin.Engine, svcCtx *svc.ServiceContext) {
	g := e.Group("/v2/file")
	g.Use(middleware.AuthorizationMiddleware)
	g.GET("/:uid/:task_id/:date/:file_name", downlaod.FileHandle(svcCtx))

}
