// Code generated by goctl. DO NOT EDIT.
package routes

import (
	"financial_statement/internal/apiserver/routes/api"
	"financial_statement/internal/apiserver/routes/captcha"
	"financial_statement/internal/apiserver/routes/file/convert"
	"financial_statement/internal/apiserver/routes/file/downlaod"
	"financial_statement/internal/apiserver/routes/setting"
	"financial_statement/internal/apiserver/routes/standard"
	"financial_statement/internal/apiserver/routes/standard/statement/formulas"
	"financial_statement/internal/apiserver/routes/standard/statement/title"
	"financial_statement/internal/apiserver/routes/task"
	"financial_statement/internal/apiserver/routes/user"
	"financial_statement/internal/apiserver/routes/user/unauthorization"
	"financial_statement/internal/apiserver/svc"

	"github.com/gin-gonic/gin"
)

func Setup(e *gin.Engine, svcCtx *svc.ServiceContext) {
	unauthorization.RegisterUserUnauthorizationRoute(e, svcCtx)
	user.RegisterUserRoute(e, svcCtx)
	task.RegisterTaskRoute(e, svcCtx)
	api.RegisterApiRoute(e, svcCtx)
	standard.RegisterStandardRoute(e, svcCtx)
	title.RegisterStandard_statement_titleRoute(e, svcCtx)
	formulas.RegisterStandard_statement_formulasRoute(e, svcCtx)
	convert.RegisterFile_convertRoute(e, svcCtx)
	downlaod.RegisterFile_downlaodRoute(e, svcCtx)
	captcha.RegisterCaptchaRoute(e, svcCtx)
	setting.RegisterSettingRoute(e, svcCtx)
}
