// Code generated by goctl. DO NOT EDIT.
package user

import (
	"financial_statement/internal/apiserver/handler/user"
	"financial_statement/internal/apiserver/middleware"
	"financial_statement/internal/apiserver/svc"

	"github.com/gin-gonic/gin"
)

func RegisterUserRoute(e *gin.Engine, svcCtx *svc.ServiceContext) {
	g := e.Group("/v2/user")
	g.Use(middleware.AuthorizationMiddleware)
	g.POST("/create", user.UserCreateHandle(svcCtx))
	g.POST("/delete", user.UserDeleteHandle(svcCtx))
	g.GET("/list", user.UserListHandle(svcCtx))
	g.GET("/:id", user.UserInfoHandle(svcCtx))
	g.POST("/update", user.UserUpdateHandle(svcCtx))
	g.POST("/status/update", user.UserStatusUpdateHandle(svcCtx))

}
