// Code generated by goctl. DO NOT EDIT.
package captcha

import (
	"financial_statement/internal/apiserver/handler/captcha"
	"financial_statement/internal/apiserver/svc"

	"github.com/gin-gonic/gin"
)

func RegisterCaptchaRoute(e *gin.Engine, svcCtx *svc.ServiceContext) {
	g := e.Group("/v2/captcha")
	g.GET("/", captcha.CaptchaHandle(svcCtx))

}
