// Code generated by goctl. DO NOT EDIT.
package standard

import (
	"financial_statement/internal/apiserver/handler/standard"
	"financial_statement/internal/apiserver/middleware"
	"financial_statement/internal/apiserver/svc"

	"github.com/gin-gonic/gin"
)

func RegisterStandardRoute(e *gin.Engine, svcCtx *svc.ServiceContext) {
	g := e.Group("/v2/standard")
	g.Use(middleware.AuthorizationMiddleware)
	g.POST("/create", standard.StandardCreateHandle(svcCtx))
	g.POST("/:id/copy", standard.StandardCopyHandle(svcCtx))
	g.PUT("/:id", standard.StandardUpdateHandle(svcCtx))
	g.POST("/:id/set_default", standard.StandardSetDefaultHandle(svcCtx))
	g.GET("/:id", standard.StandardInfoHandle(svcCtx))
	g.DELETE("/:id", standard.StandardDeleteHandle(svcCtx))
	g.GET("/list", standard.StandardListHandle(svcCtx))
	g.GET("/:id/statements", standard.StatementsHandle(svcCtx))

}
