// Code generated by goctl. DO NOT EDIT.
package api

import (
	"financial_statement/internal/apiserver/handler/api"
	"financial_statement/internal/apiserver/middleware"
	"financial_statement/internal/apiserver/svc"

	"github.com/gin-gonic/gin"
)

func RegisterApiRoute(e *gin.Engine, svcCtx *svc.ServiceContext) {
	g := e.Group("/api/v2/task")
	g.Use(middleware.AuthorizationMiddleware)
	g.POST("/create", api.TaskCreateApiHandle(svcCtx))

}
