// Code generated by goctl. DO NOT EDIT.
package task

import (
	"financial_statement/internal/apiserver/handler/task"
	"financial_statement/internal/apiserver/middleware"
	"financial_statement/internal/apiserver/svc"

	"github.com/gin-gonic/gin"
)

func RegisterTaskRoute(e *gin.Engine, svcCtx *svc.ServiceContext) {
	g := e.Group("/v2/task")
	g.Use(middleware.AuthorizationMiddleware)
	g.POST("/create", task.TaskCreateHandle(svcCtx))
	g.POST("/re-indentify", task.TaskReIdentifyHandle(svcCtx))
	g.POST("/:id/edit", task.TaskEditHandle(svcCtx))
	g.POST("/:id/rename", task.TaskReNameHandle(svcCtx))
	g.GET("/:id", task.TaskInfoHandle(svcCtx))
	g.POST("/:id/delete", task.TaskDeleteHandle(svcCtx))
	g.GET("/list", task.TaskListHandle(svcCtx))
	g.POST("/:id/group", task.TaskGroupHandle(svcCtx))
	g.POST("/:id/group/page", task.TaskGroupPageHandle(svcCtx))

}
