// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"financial_statement/internal/apiserver/dal/model"
)

func newLoginToken(db *gorm.DB) loginToken {
	_loginToken := loginToken{}

	_loginToken.loginTokenDo.UseDB(db)
	_loginToken.loginTokenDo.UseModel(&model.LoginToken{})

	tableName := _loginToken.loginTokenDo.TableName()
	_loginToken.ALL = field.NewField(tableName, "*")
	_loginToken.Token = field.NewString(tableName, "token")
	_loginToken.UserID = field.NewUint32(tableName, "user_id")
	_loginToken.CreatedAt = field.NewInt64(tableName, "created_at")
	_loginToken.Expiry = field.NewInt64(tableName, "expiry")

	_loginToken.fillFieldMap()

	return _loginToken
}

type loginToken struct {
	loginTokenDo loginTokenDo

	ALL       field.Field
	Token     field.String
	UserID    field.Uint32
	CreatedAt field.Int64
	Expiry    field.Int64

	fieldMap map[string]field.Expr
}

func (l loginToken) Table(newTableName string) *loginToken {
	l.loginTokenDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l loginToken) As(alias string) *loginToken {
	l.loginTokenDo.DO = *(l.loginTokenDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *loginToken) updateTableName(table string) *loginToken {
	l.ALL = field.NewField(table, "*")
	l.Token = field.NewString(table, "token")
	l.UserID = field.NewUint32(table, "user_id")
	l.CreatedAt = field.NewInt64(table, "created_at")
	l.Expiry = field.NewInt64(table, "expiry")

	l.fillFieldMap()

	return l
}

func (l *loginToken) WithContext(ctx context.Context) *loginTokenDo {
	return l.loginTokenDo.WithContext(ctx)
}

func (l loginToken) TableName() string { return l.loginTokenDo.TableName() }

func (l loginToken) Alias() string { return l.loginTokenDo.Alias() }

func (l *loginToken) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *loginToken) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 4)
	l.fieldMap["token"] = l.Token
	l.fieldMap["user_id"] = l.UserID
	l.fieldMap["created_at"] = l.CreatedAt
	l.fieldMap["expiry"] = l.Expiry
}

func (l loginToken) clone(db *gorm.DB) loginToken {
	l.loginTokenDo.ReplaceDB(db)
	return l
}

type loginTokenDo struct{ gen.DO }

func (l loginTokenDo) Debug() *loginTokenDo {
	return l.withDO(l.DO.Debug())
}

func (l loginTokenDo) WithContext(ctx context.Context) *loginTokenDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l loginTokenDo) ReadDB() *loginTokenDo {
	return l.Clauses(dbresolver.Read)
}

func (l loginTokenDo) WriteDB() *loginTokenDo {
	return l.Clauses(dbresolver.Write)
}

func (l loginTokenDo) Clauses(conds ...clause.Expression) *loginTokenDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l loginTokenDo) Returning(value interface{}, columns ...string) *loginTokenDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l loginTokenDo) Not(conds ...gen.Condition) *loginTokenDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l loginTokenDo) Or(conds ...gen.Condition) *loginTokenDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l loginTokenDo) Select(conds ...field.Expr) *loginTokenDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l loginTokenDo) Where(conds ...gen.Condition) *loginTokenDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l loginTokenDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *loginTokenDo {
	return l.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (l loginTokenDo) Order(conds ...field.Expr) *loginTokenDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l loginTokenDo) Distinct(cols ...field.Expr) *loginTokenDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l loginTokenDo) Omit(cols ...field.Expr) *loginTokenDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l loginTokenDo) Join(table schema.Tabler, on ...field.Expr) *loginTokenDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l loginTokenDo) LeftJoin(table schema.Tabler, on ...field.Expr) *loginTokenDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l loginTokenDo) RightJoin(table schema.Tabler, on ...field.Expr) *loginTokenDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l loginTokenDo) Group(cols ...field.Expr) *loginTokenDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l loginTokenDo) Having(conds ...gen.Condition) *loginTokenDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l loginTokenDo) Limit(limit int) *loginTokenDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l loginTokenDo) Offset(offset int) *loginTokenDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l loginTokenDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *loginTokenDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l loginTokenDo) Unscoped() *loginTokenDo {
	return l.withDO(l.DO.Unscoped())
}

func (l loginTokenDo) Create(values ...*model.LoginToken) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l loginTokenDo) CreateInBatches(values []*model.LoginToken, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l loginTokenDo) Save(values ...*model.LoginToken) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l loginTokenDo) First() (*model.LoginToken, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.LoginToken), nil
	}
}

func (l loginTokenDo) Take() (*model.LoginToken, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.LoginToken), nil
	}
}

func (l loginTokenDo) Last() (*model.LoginToken, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.LoginToken), nil
	}
}

func (l loginTokenDo) Find() ([]*model.LoginToken, error) {
	result, err := l.DO.Find()
	return result.([]*model.LoginToken), err
}

func (l loginTokenDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LoginToken, err error) {
	buf := make([]*model.LoginToken, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l loginTokenDo) FindInBatches(result *[]*model.LoginToken, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l loginTokenDo) Attrs(attrs ...field.AssignExpr) *loginTokenDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l loginTokenDo) Assign(attrs ...field.AssignExpr) *loginTokenDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l loginTokenDo) Joins(fields ...field.RelationField) *loginTokenDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l loginTokenDo) Preload(fields ...field.RelationField) *loginTokenDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l loginTokenDo) FirstOrInit() (*model.LoginToken, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.LoginToken), nil
	}
}

func (l loginTokenDo) FirstOrCreate() (*model.LoginToken, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.LoginToken), nil
	}
}

func (l loginTokenDo) FindByPage(offset int, limit int) (result []*model.LoginToken, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l loginTokenDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l loginTokenDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l loginTokenDo) Delete(models ...*model.LoginToken) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *loginTokenDo) withDO(do gen.Dao) *loginTokenDo {
	l.DO = *do.(*gen.DO)
	return l
}
