// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"financial_statement/internal/apiserver/dal/model"
)

func newStandardStatementFormula(db *gorm.DB) standardStatementFormula {
	_standardStatementFormula := standardStatementFormula{}

	_standardStatementFormula.standardStatementFormulaDo.UseDB(db)
	_standardStatementFormula.standardStatementFormulaDo.UseModel(&model.StandardStatementFormula{})

	tableName := _standardStatementFormula.standardStatementFormulaDo.TableName()
	_standardStatementFormula.ALL = field.NewField(tableName, "*")
	_standardStatementFormula.ID = field.NewUint32(tableName, "id")
	_standardStatementFormula.StatementID = field.NewUint32(tableName, "statement_id")
	_standardStatementFormula.Left = field.NewString(tableName, "left")
	_standardStatementFormula.Right = field.NewString(tableName, "right")
	_standardStatementFormula.Status = field.NewInt32(tableName, "status")
	_standardStatementFormula.CreateAt = field.NewInt64(tableName, "create_at")
	_standardStatementFormula.UpdateAt = field.NewInt64(tableName, "update_at")

	_standardStatementFormula.fillFieldMap()

	return _standardStatementFormula
}

type standardStatementFormula struct {
	standardStatementFormulaDo standardStatementFormulaDo

	ALL         field.Field
	ID          field.Uint32
	StatementID field.Uint32
	Left        field.String
	Right       field.String
	Status      field.Int32
	CreateAt    field.Int64
	UpdateAt    field.Int64

	fieldMap map[string]field.Expr
}

func (s standardStatementFormula) Table(newTableName string) *standardStatementFormula {
	s.standardStatementFormulaDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s standardStatementFormula) As(alias string) *standardStatementFormula {
	s.standardStatementFormulaDo.DO = *(s.standardStatementFormulaDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *standardStatementFormula) updateTableName(table string) *standardStatementFormula {
	s.ALL = field.NewField(table, "*")
	s.ID = field.NewUint32(table, "id")
	s.StatementID = field.NewUint32(table, "statement_id")
	s.Left = field.NewString(table, "left")
	s.Right = field.NewString(table, "right")
	s.Status = field.NewInt32(table, "status")
	s.CreateAt = field.NewInt64(table, "create_at")
	s.UpdateAt = field.NewInt64(table, "update_at")

	s.fillFieldMap()

	return s
}

func (s *standardStatementFormula) WithContext(ctx context.Context) *standardStatementFormulaDo {
	return s.standardStatementFormulaDo.WithContext(ctx)
}

func (s standardStatementFormula) TableName() string { return s.standardStatementFormulaDo.TableName() }

func (s standardStatementFormula) Alias() string { return s.standardStatementFormulaDo.Alias() }

func (s *standardStatementFormula) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *standardStatementFormula) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 7)
	s.fieldMap["id"] = s.ID
	s.fieldMap["statement_id"] = s.StatementID
	s.fieldMap["left"] = s.Left
	s.fieldMap["right"] = s.Right
	s.fieldMap["status"] = s.Status
	s.fieldMap["create_at"] = s.CreateAt
	s.fieldMap["update_at"] = s.UpdateAt
}

func (s standardStatementFormula) clone(db *gorm.DB) standardStatementFormula {
	s.standardStatementFormulaDo.ReplaceDB(db)
	return s
}

type standardStatementFormulaDo struct{ gen.DO }

func (s standardStatementFormulaDo) Debug() *standardStatementFormulaDo {
	return s.withDO(s.DO.Debug())
}

func (s standardStatementFormulaDo) WithContext(ctx context.Context) *standardStatementFormulaDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s standardStatementFormulaDo) ReadDB() *standardStatementFormulaDo {
	return s.Clauses(dbresolver.Read)
}

func (s standardStatementFormulaDo) WriteDB() *standardStatementFormulaDo {
	return s.Clauses(dbresolver.Write)
}

func (s standardStatementFormulaDo) Clauses(conds ...clause.Expression) *standardStatementFormulaDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s standardStatementFormulaDo) Returning(value interface{}, columns ...string) *standardStatementFormulaDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s standardStatementFormulaDo) Not(conds ...gen.Condition) *standardStatementFormulaDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s standardStatementFormulaDo) Or(conds ...gen.Condition) *standardStatementFormulaDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s standardStatementFormulaDo) Select(conds ...field.Expr) *standardStatementFormulaDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s standardStatementFormulaDo) Where(conds ...gen.Condition) *standardStatementFormulaDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s standardStatementFormulaDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *standardStatementFormulaDo {
	return s.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (s standardStatementFormulaDo) Order(conds ...field.Expr) *standardStatementFormulaDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s standardStatementFormulaDo) Distinct(cols ...field.Expr) *standardStatementFormulaDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s standardStatementFormulaDo) Omit(cols ...field.Expr) *standardStatementFormulaDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s standardStatementFormulaDo) Join(table schema.Tabler, on ...field.Expr) *standardStatementFormulaDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s standardStatementFormulaDo) LeftJoin(table schema.Tabler, on ...field.Expr) *standardStatementFormulaDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s standardStatementFormulaDo) RightJoin(table schema.Tabler, on ...field.Expr) *standardStatementFormulaDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s standardStatementFormulaDo) Group(cols ...field.Expr) *standardStatementFormulaDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s standardStatementFormulaDo) Having(conds ...gen.Condition) *standardStatementFormulaDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s standardStatementFormulaDo) Limit(limit int) *standardStatementFormulaDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s standardStatementFormulaDo) Offset(offset int) *standardStatementFormulaDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s standardStatementFormulaDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *standardStatementFormulaDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s standardStatementFormulaDo) Unscoped() *standardStatementFormulaDo {
	return s.withDO(s.DO.Unscoped())
}

func (s standardStatementFormulaDo) Create(values ...*model.StandardStatementFormula) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s standardStatementFormulaDo) CreateInBatches(values []*model.StandardStatementFormula, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s standardStatementFormulaDo) Save(values ...*model.StandardStatementFormula) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s standardStatementFormulaDo) First() (*model.StandardStatementFormula, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.StandardStatementFormula), nil
	}
}

func (s standardStatementFormulaDo) Take() (*model.StandardStatementFormula, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.StandardStatementFormula), nil
	}
}

func (s standardStatementFormulaDo) Last() (*model.StandardStatementFormula, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.StandardStatementFormula), nil
	}
}

func (s standardStatementFormulaDo) Find() ([]*model.StandardStatementFormula, error) {
	result, err := s.DO.Find()
	return result.([]*model.StandardStatementFormula), err
}

func (s standardStatementFormulaDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.StandardStatementFormula, err error) {
	buf := make([]*model.StandardStatementFormula, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s standardStatementFormulaDo) FindInBatches(result *[]*model.StandardStatementFormula, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s standardStatementFormulaDo) Attrs(attrs ...field.AssignExpr) *standardStatementFormulaDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s standardStatementFormulaDo) Assign(attrs ...field.AssignExpr) *standardStatementFormulaDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s standardStatementFormulaDo) Joins(fields ...field.RelationField) *standardStatementFormulaDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s standardStatementFormulaDo) Preload(fields ...field.RelationField) *standardStatementFormulaDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s standardStatementFormulaDo) FirstOrInit() (*model.StandardStatementFormula, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.StandardStatementFormula), nil
	}
}

func (s standardStatementFormulaDo) FirstOrCreate() (*model.StandardStatementFormula, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.StandardStatementFormula), nil
	}
}

func (s standardStatementFormulaDo) FindByPage(offset int, limit int) (result []*model.StandardStatementFormula, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s standardStatementFormulaDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s standardStatementFormulaDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s standardStatementFormulaDo) Delete(models ...*model.StandardStatementFormula) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *standardStatementFormulaDo) withDO(do gen.Dao) *standardStatementFormulaDo {
	s.DO = *do.(*gen.DO)
	return s
}
